version: '3'

services:
  kitchen:
    container_name: kitchen
    build: ../KitchenServer/.
    ports:
      - "5000:5000"
    volumes:
      - "../KitchenServer/./:/app"
  food-ordering:
    container_name: food-ordering
    build: ../FoodOrderingService/.
    ports:
      - "5003:5003"
    volumes:
      - "../FoodOrderingService/./:/app"
  client:
    container_name: client
    build: ./
    ports:
      - "5002:5002"
    volumes:
      - "./:/app"